### PR TITLE
ci(appveyor): Improve AppVeyor config and make it "distributable" to plugin repos

### PR DESCRIPTION
**Pull request by janpio**
This PR tries to actually run paramedic on AppVeyor/Windows the same way plugins would.

### CODE REVIEW

**Comment by janpio** [comment]
Current state on AppVeyor:

```
...
Attempting to install application...
Found package: C:\Users\appveyor\AppData\Local\Temp\1\tmp-3240y1dJFl6CoZp6\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x64_debug_Test\CordovaApp.Windows10_1.0.0.0_x64_debug.appx
Found certificate: C:\Users\appveyor\AppData\Local\Temp\1\tmp-3240y1dJFl6CoZp6\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x64_debug_Test\CordovaApp.Windows10_1.0.0.0_x64_debug.cer
Before installing this app, you need to do the following:
	- Acquire a developer license
	- Install the signing certificate
``

**Comment by janpio** [comment]
This is now only missing the equivalent to https://github.com/apache/cordova-paramedic/blob/f233020b79369a67e105ff87c39f3473728c78ad/.travis.yml#L92-L120 to be able to be used as a template both for paramedic and plugin repos.

**Comment by SACHINnANYAKKARA** [comment]
all checks are has been passed

**Comment by janpio** [comment]
I know. But https://github.com/apache/cordova-paramedic/pull/184#issuecomment-508457936 describes what is still missing from this PR.

**Comment by breautek** [comment]
I think this PR is superseded by https://github.com/apache/cordova-paramedic/pull/215

**Comment by erisu** [comment]
I also agree that this PR can be closed as AppVeyor has been dropped.

**Pull request closed without merging**
