### PR TITLE
Task/prefer physical device if connected

### PR DESCRIPTION
**Pull request by johanlantz**
If there is a physical android device connected, use it

Includes https://github.com/apache/cordova-paramedic/pull/24

### CODE REVIEW

**Comment by janpio** [comment]
If you hope for passing tests: https://github.com/apache/cordova-paramedic/pull/34 has to be merged and this branch then rebased onto `master` after that ;)

**Comment by johanlantz** [comment]
Ok, all the changes are rather small but helped a lot with getting Android to work better.

It might be faster for you to just look at the last PR and if you like the accumulated changes, simply copy paste them?

**Comment by janpio** [comment]
Ah, now I see that these are staggered pull requests - each one adding another feature. I will edit your description to reflect that.

**Comment by janpio** [comment]
This PR is currently missing the implementation of `Util.getAndroidPhysicalDevice`.

**Comment by janpio** [comment]
Seems this is it: https://github.com/Alpha-health/cordova-paramedic/blob/c103ca74624dee69b145b59864bbc45dffe71e3d/lib/utils/utilities.js#L56-L72

**Comment by janpio** [comment]
Ah, was added in your fork in a later commit as well: https://github.com/Alpha-health/cordova-paramedic/commit/66b6b278dbe5484ce35f5c7e0f6c286c2eef87e7#diff-c25f5436d57d8f3c5b863535e37855d4 

Could you please cherry pick this commit and also the following one into this branch?

https://github.com/Alpha-health/cordova-paramedic/commit/9f0dafe8caf665f2bd8523fbc30c4fff8894fad3#diff-c25f5436d57d8f3c5b863535e37855d4

That should make the file correct.

**Comment by janpio** [comment]
I think https://github.com/apache/cordova-paramedic/pull/46 is exactly what I asked for in my previous comment. So it probably makes sense to not merge this one, and just merge the other one. Correct?

**Comment by johanlantz** [comment]
Sorry about the staggered PR's. I was not sure which was the best way to send the PR's so I just took the PR's I had and created new ones back from the fork. I understand this was not optimal but hopefully the last one that contains all changes is small enough to decide if you want to integrate the changes or not.

**Comment by janpio** [comment]
It is small enough, but I still want to merge the changes feature by feature. 

But I can edit your PR branches, so I should be able to just "mangle" them until they fit our needs ;)

Thanks for opening the PRs, I will see when I can get through them all and let you know in each one what happens (or not).

**Pull request closed without merging**
