### PR TITLE
Add package.json files to plugins and plugin tests

### LINKED ISSUE #31: Testing plugins need package.json
(node 10.10 on Windows)

```
cordova-paramedic: installing plugins
cordova-paramedic: installing C:\Projects\Cordova\cordova-paramedic\spec\testable-plugin --no-telemetry --no-update-notifier
Invalid Plugin! C:\Projects\Cordova\cordova-paramedic\spec\testable-plugin needs a valid package.json
Error: Failed to install plugin : C:\Projects\Cordova\cordova-paramedic\spec\testable-plugin --no-telemetry --no-update-notifier
Completed tests at 8:34:54 PM
Collecting logs for the devices.
It looks like there is no target to get logs from.
Uninstalling the app.
Error: Failed to install plugin : C:\Projects\Cordova\cordova-paramedic\spec\testable-plugin --no-telemetry --no-update-notifier
    at PluginsManager.installSinglePlugin (C:\Projects\Cordova\cordova-paramedic\lib\PluginsManager.js:85:15)
    at PluginsManager.installPlugins (C:\Projects\Cordova\cordova-paramedic\lib\PluginsManager.js:37:14)
    at ParamedicRunner.installPlugins (C:\Projects\Cordova\cordova-paramedic\lib\paramedic.js:158:25)
    at ParamedicRunner.prepareProjectToRunTests (C:\Projects\Cordova\cordova-paramedic\lib\paramedic.js:147:10)
    at C:\Projects\Cordova\cordova-paramedic\lib\paramedic.js:75:21
    at _fulfilled (C:\Projects\Cordova\cordova-paramedic\node_modules\q\q.js:854:54)
    at C:\Projects\Cordova\cordova-paramedic\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Projects\Cordova\cordova-paramedic\node_modules\q\q.js:816:13)
    at C:\Projects\Cordova\cordova-paramedic\node_modules\q\q.js:877:14
    at runSingle (C:\Projects\Cordova\cordova-paramedic\node_modules\q\q.js:137:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cordova-paramedic@0.5.0 test-ios: `node main.js --platform ios --plugin ./spec/testable-plugin/ --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cordova-paramedic@0.5.0 test-ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Plugins in `/spec` are all missing a `package.json` file.

### PR DESCRIPTION
**Pull request by janpio**
This PR adds the most rudimentary package.json possible for plugins and plugin tests.

fixes #31

### CODE REVIEW

**Comment by janpio** [comment]
That is indeed true - but I am looking forward to changing that (or merging a PR that changes that. Any ideas?)

**Comment by NiklasMerz** [comment]
At first it sounds complicated to test a test framework/tool. To me test are already beneficial to see if everything builds correctly. 

Maybe we could add more functions to the plugins in the test folder, to test some cases. I think @purplecabbage already started to do that. We should have some successful and some failing tests in those plugins to at least cover some basics of testing.

(I could try to do some experiments when I find time in the next days)

**Comment by purplecabbage** [comment]
I believe part of the issue here was just that cordova now expects plugins to have package.json files.
There are several tests which cover, an iOS plugin, with a build error, that should fail. 
This definitely could be expanded to handle more cases.  I would start by adding coverage just so we can see what modules/functions are not being tested.
😸 
https://github.com/apache/cordova-paramedic/blob/master/spec/testable-plugin/tests/tests.js#L34

**Comment by janpio** [comment]
package.json is now fixed an Travis is green 💚 

AppVeyor still needs some work though: https://github.com/apache/cordova-paramedic/issues/37

Adding coverage is great idea.

**Pull request merged**
