### PR TITLE
Fix some npm audit issues (upgrade dependencies)

### PR DESCRIPTION
**Pull request by NiklasMerz**
### What does this PR do?
Fixes issues raised by `npm audit`.

### What testing has been done on this change?
Testing two plugins with the updated version of paramedic. See: https://github.com/apache/cordova-paramedic/pull/40#issuecomment-426030119

### CODE REVIEW

**Comment by NiklasMerz** [comment]
I agreee. I just deleted the file.

**Comment by janpio** [comment]
great.

jasmine and socket.io are major upgrades. no problems with that?

**Comment by NiklasMerz** [comment]
As far as I remember everything was fine. I will do some tests tonight and report back.

**Comment by NiklasMerz** [comment]
I added the branch to two plugins and the builds ran fine locally and on travis. Some audit issues for these plugins disappeared.

https://travis-ci.org/GEDYSIntraWare/cordova-plugin-call-directory/builds/435785244

https://travis-ci.org/NiklasMerz/cordova-plugin-fingerprint-aio/builds/435782826

I think this is fine but you could do some tests, too. I am not that familiar with testing and paramedic.

**Comment by janpio** [comment]
I had to revert this because the users of cordova-paramedic are on a too old node:

```
0.25s$ node /tmp/paramedic/main.js --config pr/$PLATFORM --plugin $(pwd) --shouldUseSauce --buildName travis-plugin-inappbrowser-$TRAVIS_JOB_NUMBER
/tmp/paramedic/node_modules/socket.io/node_modules/debug/src/node.js:132
	let val = process.env[key];
	^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/paramedic/node_modules/socket.io/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

As this is all over the place, fixing this will take some time :/

Any idea how to solve this?

**Comment by NiklasMerz** [comment]
Maybe we should find the latest version that works with this node version. Which version is it anyway?

I will look into it.

**Comment by NiklasMerz** [comment]
@janpio Do you still know which node version is a problem. It looks like the old socket.io version is problem.

**Comment by NiklasMerz** [comment]
Do you know why this version is that old? Any chance to raise that version? I see all kinds of packages breaking with 4.2.

**Comment by janpio** [comment]
It just a lot of work to go through all the CI configurations of all the plugins and update that number - and deal with possible fallout. As some of those users are also directly cloning from master here, we are currently a bit blocked by this.

**Comment by NiklasMerz** [comment]
That`s unfortunate. I don´t think updating the dependencies to work with node 4 and fix the issues is possible.

**Comment by janpio** [comment]
That's fine, just reopen your PR and note that it should only be merged when we dropped support for and use of npm 4.x - this will happen sooner or later.

**Pull request merged**
